#!/bin/bash

docuIndexYamlHeader="---
IMPORTANT: This file is generated by \`./docu.sh\`. Please don't edit it manually!

title: FsHttp Overview
index: 1
---

"
readmeContent=$(cat ./README.md)
echo "$docuIndexYamlHeader$readmeContent" > ./docs/index.md

if [ -d ./.fsdocs ]; then
    rm -rf ./.fsdocs
fi

dotnet tool restore
dotnet build ./src/FsHttp/FsHttp.fsproj -c Release -f net8.0

# what a hack...
if [ -z "$1" ]; then
    mode="build"
else
    mode="watch"
fi

dotnet fsdocs \
    $mode \
    --clean \
    --sourcefolder ./src \
    --properties Configuration=Release TargetFramework=net8.0 \
    --sourcerepo https://github.com/fsprojects/FsHttp/blob/master/src \
    --parameters root /FsHttp/ \
    --output ./.docsOutput \
    --ignoreprojects Test.CSharp.csproj \
    --strict
    